name: remove
description: A library that makes the dumbest and simplest variable definition possible.
version: 1.0.8
repository: https://github.com/SnapLan/remove
issue_tracker: https://github.com/SnapLan/remove/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.19.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
